CREATE PROC JUGADOR_INSERTAR
@id int
as
BEGIN
	declare @PG int, @PE int, @PP int
	set @PG = 0
	set @PE = 0
	set @PP = 0
	
	INSERT INTO JUGADOR (ID_USUARIO, PARTIDAS_GANADAS, PARTIDAS_EMPATADAS, PARTIDAS_PERDIDAS)
	VALUES (@id, @PG, @PE, @PP)
END