USE [master]
GO
/****** Object:  Database [BatallaNaval]    Script Date: 22/10/2025 11:53:18 ******/
CREATE DATABASE [BatallaNaval]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BatallaNaval', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BatallaNaval.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BatallaNaval_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BatallaNaval_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BatallaNaval] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BatallaNaval].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BatallaNaval] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BatallaNaval] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BatallaNaval] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BatallaNaval] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BatallaNaval] SET ARITHABORT OFF 
GO
ALTER DATABASE [BatallaNaval] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BatallaNaval] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BatallaNaval] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BatallaNaval] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BatallaNaval] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BatallaNaval] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BatallaNaval] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BatallaNaval] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BatallaNaval] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BatallaNaval] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BatallaNaval] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BatallaNaval] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BatallaNaval] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BatallaNaval] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BatallaNaval] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BatallaNaval] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BatallaNaval] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BatallaNaval] SET RECOVERY FULL 
GO
ALTER DATABASE [BatallaNaval] SET  MULTI_USER 
GO
ALTER DATABASE [BatallaNaval] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BatallaNaval] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BatallaNaval] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BatallaNaval] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BatallaNaval] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BatallaNaval] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BatallaNaval', N'ON'
GO
ALTER DATABASE [BatallaNaval] SET QUERY_STORE = ON
GO
ALTER DATABASE [BatallaNaval] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BatallaNaval]
GO
/****** Object:  Table [dbo].[JUGADOR]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JUGADOR](
	[ID_USUARIO] [int] NOT NULL,
	[PARTIDAS_GANADAS] [int] NOT NULL,
	[PARTIDAS_EMPATADAS] [int] NOT NULL,
	[PARTIDAS_PERDIDAS] [int] NOT NULL,
 CONSTRAINT [PK_JUGADOR] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[CONTRASEÑA] [varchar](50) NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JUGADOR]  WITH CHECK ADD  CONSTRAINT [FK_JUGADOR_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[JUGADOR] CHECK CONSTRAINT [FK_JUGADOR_USUARIO]
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_BORRAR]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_BORRAR]
@id int
as
BEGIN
	delete from USUARIO where ID_USUARIO = @id
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_BUSCAR]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_BUSCAR]
@nom varchar(50), @pass varchar(50)
as
BEGIN
	select ID_USUARIO, NOMBRE, CONTRASEÑA from USUARIO
	where NOMBRE = @nom and CONTRASEÑA = @pass
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_EDITAR]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_EDITAR]
@id int, @nom varchar(50), @pass varchar(50)
as
BEGIN
	UPDATE USUARIO SET
	NOMBRE = @nom,
	CONTRASEÑA = @pass
	WHERE ID_USUARIO = @id
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_INSERTAR]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_INSERTAR]
@nom varchar(50), @pass varchar(50)
as
BEGIN
	declare @id int
	set @id = (select isnull(max(ID_USUARIO), 0) + 1 from USUARIO)

	 INSERT INTO USUARIO (ID_USUARIO, NOMBRE, CONTRASEÑA) VALUES (@id, @nom, @pass)
END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR]    Script Date: 22/10/2025 11:53:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_LISTAR]
as
BEGIN
	SELECT ID_USUARIO, NOMBRE, CONTRASEÑA FROM USUARIO
END
GO
USE [master]
GO
ALTER DATABASE [BatallaNaval] SET  READ_WRITE 
GO
