
USE [BASE]
GO
/****** Object:  Table [dbo].[DETALLE]    Script Date: 27/8/2025 20:42:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETALLE](
	[ID_FACTURA] [int] NOT NULL,
	[ID_DETALLE] [int] NOT NULL,
	[ID_PRODUCTO] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
 CONSTRAINT [PK_DETALLE] PRIMARY KEY CLUSTERED 
(
	[ID_FACTURA] ASC,
	[ID_DETALLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACTURA]    Script Date: 27/8/2025 20:42:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACTURA](
	[ID_FACTURA] [int] NOT NULL,
	[Numero] [int] NOT NULL,
 CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED 
(
	[ID_FACTURA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 27/8/2025 20:42:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[ID_PRODUCTO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[PRECIO] [float] NOT NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_DETALLE_FACTURA] FOREIGN KEY([ID_FACTURA])
REFERENCES [dbo].[FACTURA] ([ID_FACTURA])
GO
ALTER TABLE [dbo].[DETALLE] CHECK CONSTRAINT [FK_DETALLE_FACTURA]
GO
ALTER TABLE [dbo].[DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_DETALLE_PRODUCTO] FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[PRODUCTO] ([ID_PRODUCTO])
GO
ALTER TABLE [dbo].[DETALLE] CHECK CONSTRAINT [FK_DETALLE_PRODUCTO]
GO
/****** Object:  StoredProcedure [dbo].[DETALLE_INSERTAR]    Script Date: 27/8/2025 20:42:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[DETALLE_INSERTAR]
@ID_FACTURA int, @ID_PRODUCTO int, @CANTIDAD int
as
BEGIN

if exists(select * from DETALLE 
		 where ID_FACTURA = @ID_FACTURA
         and ID_PRODUCTO= @ID_PRODUCTO)
begin
	update DETALLE set
	cantidad += @CANTIDAD
	where ID_FACTURA = @ID_FACTURA
         and ID_PRODUCTO= @ID_PRODUCTO
end
else	
begin 

	declare @id int
	set @id = (select ISNULL(max(id_detalle),0)+1 from DETALLE
				where ID_FACTURA = @ID_FACTURA)

	insert into DETALLE (ID_FACTURA,ID_DETALLE,ID_PRODUCTO, Cantidad)
	values (@ID_FACTURA, @id,@ID_PRODUCTO,@CANTIDAD)
end

END
GO
/****** Object:  StoredProcedure [dbo].[FACTURA_INSERTAR]    Script Date: 27/8/2025 20:42:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[FACTURA_INSERTAR]
@NUMERO int, @id int out
as
BEGIN


SET @id = (SELECT ISNULL(MAX(ID_FACTURA),0) +1 FROM FACTURA )

INSERT INTO FACTURA (ID_FACTURA,Numero)
values (@id,@NUMERO)
END
GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_LISTAR]    Script Date: 27/8/2025 20:42:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PRODUCTO_LISTAR]
as 
BEGIN 
	SELECT ID_PRODUCTO, NOMBRE, PRECIO
	FROM PRODUCTO

END
GO
USE [master]
GO
ALTER DATABASE [BASE] SET  READ_WRITE 
GO
