USE [master]
GO
/****** Object:  Database [BASE3]    Script Date: 21/10/2025 0:53:42 ******/
CREATE DATABASE [BASE3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BASE3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BASE3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BASE3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BASE3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BASE3] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BASE3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BASE3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BASE3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BASE3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BASE3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BASE3] SET ARITHABORT OFF 
GO
ALTER DATABASE [BASE3] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BASE3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BASE3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BASE3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BASE3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BASE3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BASE3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BASE3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BASE3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BASE3] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BASE3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BASE3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BASE3] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BASE3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BASE3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BASE3] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BASE3] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BASE3] SET RECOVERY FULL 
GO
ALTER DATABASE [BASE3] SET  MULTI_USER 
GO
ALTER DATABASE [BASE3] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BASE3] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BASE3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BASE3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BASE3] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BASE3] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BASE3', N'ON'
GO
ALTER DATABASE [BASE3] SET QUERY_STORE = ON
GO
ALTER DATABASE [BASE3] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BASE3]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONA_TITULO]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA_TITULO](
	[ID_P] [int] NOT NULL,
	[ID_T] [int] NOT NULL,
 CONSTRAINT [PK_PERSONA_TITULO] PRIMARY KEY CLUSTERED 
(
	[ID_P] ASC,
	[ID_T] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TITULO]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TITULO](
	[ID] [int] NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TITULO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[PERSONA] ([ID], [NOMBRE], [APELLIDO]) VALUES (1, N'Christian', N'Parkinson')
GO
INSERT [dbo].[PERSONA_TITULO] ([ID_P], [ID_T]) VALUES (1, 1)
GO
INSERT [dbo].[PERSONA_TITULO] ([ID_P], [ID_T]) VALUES (1, 3)
GO
INSERT [dbo].[TITULO] ([ID], [DESCRIPCION]) VALUES (1, N'ING. EN SISTEMAS')
GO
INSERT [dbo].[TITULO] ([ID], [DESCRIPCION]) VALUES (2, N'ANALISTA EN SISTEMAS')
GO
INSERT [dbo].[TITULO] ([ID], [DESCRIPCION]) VALUES (3, N'Lic. en sistemas')
GO
INSERT [dbo].[TITULO] ([ID], [DESCRIPCION]) VALUES (4, N'SOCIOLOGIA')
GO
INSERT [dbo].[TITULO] ([ID], [DESCRIPCION]) VALUES (5, N'MUSICOTERAPIA')
GO
ALTER TABLE [dbo].[PERSONA_TITULO]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_TITULO_PERSONA] FOREIGN KEY([ID_P])
REFERENCES [dbo].[PERSONA] ([ID])
GO
ALTER TABLE [dbo].[PERSONA_TITULO] CHECK CONSTRAINT [FK_PERSONA_TITULO_PERSONA]
GO
ALTER TABLE [dbo].[PERSONA_TITULO]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_TITULO_TITULO] FOREIGN KEY([ID_T])
REFERENCES [dbo].[TITULO] ([ID])
GO
ALTER TABLE [dbo].[PERSONA_TITULO] CHECK CONSTRAINT [FK_PERSONA_TITULO_TITULO]
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_INSERTAR]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PERSONA_INSERTAR]
@nom varchar(50), @ape varchar(50)
as
BEGIN
	declare @id int
	set @id = (select isnull(max(id), 0) +1 from PERSONA)

	insert into PERSONA (ID, NOMBRE, APELLIDO) values (@id,@nom,@ape)
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_OBTENERMAXID]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PERSONA_OBTENERMAXID]
as
BEGIN
	select isnull(max(id), 0) from PERSONA
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_TITULO_INSERTAR]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PERSONA_TITULO_INSERTAR]
@id int, @id_t int
as
BEGIN
	INSERT INTO PERSONA_TITULO (ID_P,ID_T) VALUES (@id, @id_t)
END
GO
/****** Object:  StoredProcedure [dbo].[TITULO_INSERTAR]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[TITULO_INSERTAR] --crear procedimiento almacenado llamado "TITULO_INSERTAR"
@titulo varchar(50) --parametros que va a recibir mi procedimiento
as
BEGIN
	--declaro la variable @id con la palabra reservada "declare"
	declare @id int
	--para asignarle un valor a mi variable se usa la palabra reservada "set"
	set @id = (select isnull(max(id), 0) + 1 from titulo)

	--existe un elemento en la base?
	declare @existe int
	set @existe = (select count(*) from TITULO where DESCRIPCION = @titulo)

	if @existe = 0
	BEGIN
		INSERT INTO TITULO (ID, DESCRIPCION) VALUES (@id, @titulo)
	END
END
GO
/****** Object:  StoredProcedure [dbo].[TITULO_LISTAR]    Script Date: 21/10/2025 0:53:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[TITULO_LISTAR]
as
BEGIN
	SELECT * FROM TITULO
END
GO
USE [master]
GO
ALTER DATABASE [BASE3] SET  READ_WRITE 
GO
