--con la palabra reservarda "exec" podemos ejecutar procedimientos almacenados
exec TITULO_INSERTAR 'ING. EN SISTEMAS'

BEGIN TRAN --INICIAR TRANSACCION
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'
exec TITULO_INSERTAR 'ANALISTA EN SISTEMAS'

delete from TITULO where id > 2

COMMIT TRAN --CONFIRMAR TRANSACCION

ROLLBACK TRAN --DESHACER TRANSACCION
select * from TITULO