SELECT * FROM USUARIO WHERE NOMBRE = 'Christian' and CONTRASEÑA = '123'

SELECT * FROM USUARIO WHERE NOMBRE = '' or 1=1 --' and CONTRASEÑA = '3245675324567'

--selecciona el ID maximo del usuario
SELECT MAX(ID) FROM USUARIO

--le incrementamos uno para conocer el siguiente
SELECT MAX(ID) +1 FROM USUARIO

--SI EL MAX ID ES NULL (NO HAY USUARIOS GUARDADOS), QUE LO REEMPLACE POR CERO (0) Y LE SUME UNO DESPUES
SELECT ISNULL(MAX(ID), 0) +1 FROM USUARIO

delete from USUARIO