SELECT * FROM PERSONA

SELECT ID_PERSONA, NOMBRE, APELLIDO, EDAD FROM PERSONA
SELECT ID_PERSONA, NOMBRE, APELLIDO FROM PERSONA
SELECT ID_PERSONA, NOMBRE FROM PERSONA
SELECT NOMBRE, APELLIDO FROM PERSONA

INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, EDAD) VALUES (1, 'CHRISTIAN', 'PARKINSON', 43)
INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, EDAD) VALUES (2, 'CLOE', 'PARKINSON', 7)
INSERT INTO PERSONA (ID_PERSONA, NOMBRE, APELLIDO, EDAD) VALUES (3, 'GAEL', 'PARKINSON', 13)

UPDATE PERSONA SET EDAD = 8 WHERE ID_PERSONA = 2