USE [BASE2]
GO
/****** Object:  Table [dbo].[PEDIDO]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PEDIDO](
	[ID_PEDIDO] [int] NOT NULL,
	[ID_PRODUCTO] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
 CONSTRAINT [PK_PEDIDO] PRIMARY KEY CLUSTERED 
(
	[ID_PEDIDO] ASC,
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[ID_PRODUCTO] [int] NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[Contraseña] [varchar](50) NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [DESCRIPCION]) VALUES (1, N'PANCHO')
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [DESCRIPCION]) VALUES (2, N'MILANESA')
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [DESCRIPCION]) VALUES (4, N'PIZZA')
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [DESCRIPCION]) VALUES (5, N'ÑOQUIS')
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [DESCRIPCION]) VALUES (6, N'MILANESA A LA NAPOLITANA CON FRITAS')
GO
INSERT [dbo].[USUARIO] ([ID_USUARIO], [NOMBRE], [Contraseña]) VALUES (1, N'CHRISTIAN', N'666')
GO
INSERT [dbo].[USUARIO] ([ID_USUARIO], [NOMBRE], [Contraseña]) VALUES (2, N'SUSY', N'123')
GO
ALTER TABLE [dbo].[PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDO_PRODUCTO] FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[PRODUCTO] ([ID_PRODUCTO])
GO
ALTER TABLE [dbo].[PEDIDO] CHECK CONSTRAINT [FK_PEDIDO_PRODUCTO]
GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_BORRAR]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PRODUCTO_BORRAR]
@id int
as
begin
	DELETE FROM PRODUCTO 
	where ID_PRODUCTO = @id
end
GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_EDITAR]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PRODUCTO_EDITAR]
@id int, @nom varchar(50)
as
begin
	update PRODUCTO set
	DESCRIPCION = @nom
	where ID_PRODUCTO = @id
end

GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_INSERTAR]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PRODUCTO_INSERTAR]
@nombre varchar(50)
as 
BEGIN

declare @id int

set @id = (select isnull(max(id_producto),0) +1 from PRODUCTO)

if not exists(select * from PRODUCTO where DESCRIPCION = @nombre)
begin
	insert into PRODUCTO (ID_PRODUCTO,DESCRIPCION)
	values (@id,@nombre)
end
else
begin
	print ('LA DESCRIPCION EXISTE')
end
END
GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_LISTAR]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PRODUCTO_LISTAR]
as 
BEGIN

SELECT ID_PRODUCTO, DESCRIPCION FROM PRODUCTO 

END
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR]    Script Date: 20/8/2025 22:09:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_LISTAR]
@usu varchar(50), @pass varchar(50)
as 
BEGIN

SELECT COUNT(*) FROM USUARIO WHERE NOMBRE = @usu and Contraseña = @pass

END
GO
USE [master]
GO
ALTER DATABASE [BASE2] SET  READ_WRITE 
GO
